apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-recreate-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: student-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

